var faker = require('faker');

exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('reviews').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)}),
        knex('reviews').insert({rating: Math.random() * 5, review: faker.lorem.paragraph(), restaurant_id: Math.ceil(Math.random() * 12), user_id: Math.ceil(Math.random() * 20)})
      ]);
    });
};
